[common]
; log level: 0=off, 1=errors, 2=errors+warnings, 3=info, 4=verbose
logLevel=0

; show scratched (deleted) files with .prg extension
showScratchedFiles=0

; ONLY show scratched files (no other files)
showONLYScratchedFiles=0

; always append .prg extension (even to PRG files)
appendPrgExtension=0

; ignore error codes from error table if available
ignoreErrorTable=0

; fill deleted file sectors with 0x00 on delete
eraseDeletedSectors=0
